const datas2 = [
  {
    id: 1,
    product_name: "Cilantro / Coriander - Fresh",
    product_number: "65bb40e6fc13ae52c123463e",
    product_category: "Pelargonium peltatum (L.) L'Hér. ex Aiton",
    product_weight: "29",
    product_price: "56",
  },
]


const datas = [
  {
    id: 1,
    product_name: "Cilantro / Coriander - Fresh",
    product_number: { $oid: "65bb40e6fc13ae52c123463e" },
    product_category: "Pelargonium peltatum (L.) L'Hér. ex Aiton",
    product_weight: 29,
    product_price: 56,
  },
  {
    id: 2,
    product_name: "Hog / Sausage Casing - Pork",
    product_number: { $oid: "65bb40e6fc13ae52c123463f" },
    product_category: "Arthonia subminutula Nyl.",
    product_weight: 79,
    product_price: 16,
  },
  {
    id: 3,
    product_name: "Nut - Almond, Blanched, Whole",
    product_number: { $oid: "65bb40e6fc13ae52c1234640" },
    product_category: "Brickellia betonicifolia A. Gray",
    product_weight: 86,
    product_price: 42,
  },
  {
    id: 4,
    product_name: "Neckerchief Blck",
    product_number: { $oid: "65bb40e6fc13ae52c1234641" },
    product_category: "Tolmiea menziesii (Pursh) Torr. & A. Gray",
    product_weight: 96,
    product_price: 8,
  },
  {
    id: 5,
    product_name: "Beef - Top Butt",
    product_number: { $oid: "65bb40e6fc13ae52c1234642" },
    product_category:
      "Luzula arcuata (Wahlenb.) Sw. ssp. unalaschcensis (Buchenau) Hultén",
    product_weight: 97,
    product_price: 20,
  },
  {
    id: 6,
    product_name: "Wine - Piper Heidsieck Brut",
    product_number: { $oid: "65bb40e6fc13ae52c1234643" },
    product_category: "Sanicula smallii E.P. Bicknell",
    product_weight: 78,
    product_price: 68,
  },
  {
    id: 7,
    product_name: "Wine - Ice Wine",
    product_number: { $oid: "65bb40e6fc13ae52c1234644" },
    product_category: "Arabis williamsii Rollins",
    product_weight: 70,
    product_price: 79,
  },
  {
    id: 8,
    product_name: "Puree - Pear",
    product_number: { $oid: "65bb40e6fc13ae52c1234645" },
    product_category: "Epidendrum floridense Hágsater",
    product_weight: 96,
    product_price: 31,
  },
  {
    id: 9,
    product_name: "Wine - Ej Gallo Sonoma",
    product_number: { $oid: "65bb40e6fc13ae52c1234646" },
    product_category: "Hypnum pratense (Rabenh.) Koch ex Spruce",
    product_weight: 53,
    product_price: 34,
  },
  {
    id: 10,
    product_name: "Beer - Alexander Kieths, Pale Ale",
    product_number: { $oid: "65bb40e6fc13ae52c1234647" },
    product_category: "Astragalus gambelianus Sheldon",
    product_weight: 5,
    product_price: 46,
  },
  {
    id: 11,
    product_name: "Jam - Raspberry,jar",
    product_number: { $oid: "65bb40e6fc13ae52c1234648" },
    product_category: "Taxodium Rich.",
    product_weight: 78,
    product_price: 39,
  },
  {
    id: 12,
    product_name: "Guava",
    product_number: { $oid: "65bb40e6fc13ae52c1234649" },
    product_category: "Rinodina colobina (Ach.) Th. Fr.",
    product_weight: 71,
    product_price: 27,
  },
  {
    id: 13,
    product_name: "Apple - Custard",
    product_number: { $oid: "65bb40e6fc13ae52c123464a" },
    product_category:
      "Coreopsis pubescens Elliott var. robusta A. Gray ex Eames",
    product_weight: 71,
    product_price: 59,
  },
  {
    id: 14,
    product_name: "Nut - Walnut, Chopped",
    product_number: { $oid: "65bb40e6fc13ae52c123464b" },
    product_category: "Vaccinium ×marianum S. Watson (pro sp.)",
    product_weight: 13,
    product_price: 31,
  },
  {
    id: 15,
    product_name: "Sloe Gin - Mcguinness",
    product_number: { $oid: "65bb40e6fc13ae52c123464c" },
    product_category: "Eriophorum callitrix Cham. ex C.A. Mey. var. callitrix",
    product_weight: 21,
    product_price: 30,
  },
  {
    id: 16,
    product_name: "Pasta - Cannelloni, Sheets, Fresh",
    product_number: { $oid: "65bb40e6fc13ae52c123464d" },
    product_category: "Fulgensia fulgens (Sw.) Elenkin",
    product_weight: 84,
    product_price: 18,
  },
  {
    id: 17,
    product_name: "Ginger - Pickled",
    product_number: { $oid: "65bb40e6fc13ae52c123464e" },
    product_category: "Rhynchosia caribaea (Jacq.) DC.",
    product_weight: 10,
    product_price: 64,
  },
  {
    id: 18,
    product_name: "Pasta - Cheese / Spinach Bauletti",
    product_number: { $oid: "65bb40e6fc13ae52c123464f" },
    product_category: "Calochortus weedii Alph. Wood var. weedii",
    product_weight: 63,
    product_price: 18,
  },
  {
    id: 19,
    product_name: "Yukon Jack",
    product_number: { $oid: "65bb40e6fc13ae52c1234650" },
    product_category:
      "Tetramolopium humile (A. Gray) Hillebr. ssp. humile var. sublaeve Sherff",
    product_weight: 22,
    product_price: 42,
  },
  {
    id: 20,
    product_name: "Galliano",
    product_number: { $oid: "65bb40e6fc13ae52c1234651" },
    product_category: "Tragia nepetifolia Cav.",
    product_weight: 41,
    product_price: 88,
  },
  {
    id: 21,
    product_name: "Butter Balls Salted",
    product_number: { $oid: "65bb40e6fc13ae52c1234652" },
    product_category: "Venturiella sinensis (Vent.) Müll. Hal.",
    product_weight: 73,
    product_price: 78,
  },
  {
    id: 22,
    product_name: "Eel Fresh",
    product_number: { $oid: "65bb40e6fc13ae52c1234653" },
    product_category:
      "Solidago simplex Kunth ssp. randii (Porter) Ringius var. randii (Porter) Kartesz & Gandhi",
    product_weight: 84,
    product_price: 18,
  },
  {
    id: 23,
    product_name: "Bread - White, Unsliced",
    product_number: { $oid: "65bb40e6fc13ae52c1234654" },
    product_category: "Euryale Salisb.",
    product_weight: 68,
    product_price: 16,
  },
  {
    id: 24,
    product_name: "Tarragon - Fresh",
    product_number: { $oid: "65bb40e6fc13ae52c1234655" },
    product_category: "Cymopterus davisii R.L. Hartm.",
    product_weight: 40,
    product_price: 66,
  },
  {
    id: 25,
    product_name: "Bread Base - Italian",
    product_number: { $oid: "65bb40e6fc13ae52c1234656" },
    product_category: "Cruciata Mill.",
    product_weight: 38,
    product_price: 79,
  },
  {
    id: 26,
    product_name: "Venison - Striploin",
    product_number: { $oid: "65bb40e6fc13ae52c1234657" },
    product_category: "Chamaesaracha villosa Rydb.",
    product_weight: 36,
    product_price: 6,
  },
  {
    id: 27,
    product_name: "Amarula Cream",
    product_number: { $oid: "65bb40e6fc13ae52c1234658" },
    product_category: "Lotus crassifolius (Benth.) Greene var. crassifolius",
    product_weight: 14,
    product_price: 30,
  },
  {
    id: 28,
    product_name: "Banana",
    product_number: { $oid: "65bb40e6fc13ae52c1234659" },
    product_category: "Senecio cannabifolius Less.",
    product_weight: 65,
    product_price: 56,
  },
  {
    id: 29,
    product_name: "Basil - Seedlings Cookstown",
    product_number: { $oid: "65bb40e6fc13ae52c123465a" },
    product_category: "Atriplex nuttallii S. Watson",
    product_weight: 7,
    product_price: 82,
  },
  {
    id: 30,
    product_name: "Mussels - Frozen",
    product_number: { $oid: "65bb40e6fc13ae52c123465b" },
    product_category: "Phacelia umbrosa Greene",
    product_weight: 70,
    product_price: 16,
  },
  {
    id: 31,
    product_name: "Turkey - Breast, Boneless Sk On",
    product_number: { $oid: "65bb40e6fc13ae52c123465c" },
    product_category: "Mnium stellare Hedw.",
    product_weight: 63,
    product_price: 30,
  },
  {
    id: 32,
    product_name: "Juice Peach Nectar",
    product_number: { $oid: "65bb40e6fc13ae52c123465d" },
    product_category:
      "Lupinus sericeus Pursh ssp. sericeus var. maximus C.P. Sm. ex Fleak & D. Dunn",
    product_weight: 45,
    product_price: 10,
  },
  {
    id: 33,
    product_name: "Capon - Whole",
    product_number: { $oid: "65bb40e6fc13ae52c123465e" },
    product_category: "Jacquemontia Choisy",
    product_weight: 82,
    product_price: 86,
  },
  {
    id: 34,
    product_name: "Wine - White, Ej",
    product_number: { $oid: "65bb40e6fc13ae52c123465f" },
    product_category: "Viola wailenalenae (Rock) Skottsb.",
    product_weight: 77,
    product_price: 21,
  },
  {
    id: 35,
    product_name: "Toamtoes 6x7 Select",
    product_number: { $oid: "65bb40e6fc13ae52c1234660" },
    product_category:
      "Calycanthus floridus L. var. glaucus (Willd.) Torr. & A. Gray",
    product_weight: 95,
    product_price: 78,
  },
  {
    id: 36,
    product_name: "Bread - Raisin Walnut Pull",
    product_number: { $oid: "65bb40e6fc13ae52c1234661" },
    product_category: "Hexastylis contracta Blomquist",
    product_weight: 29,
    product_price: 9,
  },
  {
    id: 37,
    product_name: "Cheese - Sheep Milk",
    product_number: { $oid: "65bb40e6fc13ae52c1234662" },
    product_category: "Alstonia R. Br.",
    product_weight: 8,
    product_price: 75,
  },
  {
    id: 38,
    product_name: "Maintenance Removal Charge",
    product_number: { $oid: "65bb40e6fc13ae52c1234663" },
    product_category: "Betula ×utahensis Britton (pro sp.)",
    product_weight: 34,
    product_price: 20,
  },
  {
    id: 39,
    product_name: "Chips Potato Salt Vinegar 43g",
    product_number: { $oid: "65bb40e6fc13ae52c1234664" },
    product_category: "Mikania stevensiana Britton",
    product_weight: 87,
    product_price: 97,
  },
  {
    id: 40,
    product_name: "Spice - Paprika",
    product_number: { $oid: "65bb40e6fc13ae52c1234665" },
    product_category: "Miconia Ruiz & Pav.",
    product_weight: 29,
    product_price: 65,
  },
  {
    id: 41,
    product_name: "Pepper - Pablano",
    product_number: { $oid: "65bb40e6fc13ae52c1234666" },
    product_category: "Ephedra torreyana S. Watson",
    product_weight: 23,
    product_price: 24,
  },
  {
    id: 42,
    product_name: "Papayas",
    product_number: { $oid: "65bb40e6fc13ae52c1234667" },
    product_category:
      "Lindsaea stricta (Sw.) Dryand. ex Sm. var. jamesoniiformis Kramer",
    product_weight: 29,
    product_price: 51,
  },
  {
    id: 43,
    product_name: "Sardines",
    product_number: { $oid: "65bb40e6fc13ae52c1234668" },
    product_category: "Miconia impetiolaris (Sw.) D. Don ex DC.",
    product_weight: 12,
    product_price: 67,
  },
  {
    id: 44,
    product_name: "Basil - Seedlings Cookstown",
    product_number: { $oid: "65bb40e6fc13ae52c1234669" },
    product_category: "Sibara grisea Rollins",
    product_weight: 74,
    product_price: 35,
  },
  {
    id: 45,
    product_name: "Wooden Mop Handle",
    product_number: { $oid: "65bb40e6fc13ae52c123466a" },
    product_category: "Peperomia remyi C. DC.",
    product_weight: 88,
    product_price: 75,
  },
  {
    id: 46,
    product_name: "Tea - Mint",
    product_number: { $oid: "65bb40e6fc13ae52c123466b" },
    product_category: "Nephelium lappaceum L.",
    product_weight: 32,
    product_price: 93,
  },
  {
    id: 47,
    product_name: "Beef - Diced",
    product_number: { $oid: "65bb40e6fc13ae52c123466c" },
    product_category: "Hordeum arizonicum Covas",
    product_weight: 28,
    product_price: 92,
  },
  {
    id: 48,
    product_name: "Crab - Blue, Frozen",
    product_number: { $oid: "65bb40e6fc13ae52c123466d" },
    product_category: "Cleome sparsifolia S. Watson",
    product_weight: 32,
    product_price: 49,
  },
  {
    id: 49,
    product_name: "Beer - Tetleys",
    product_number: { $oid: "65bb40e6fc13ae52c123466e" },
    product_category: "Euphorbia resinifera Berg",
    product_weight: 52,
    product_price: 36,
  },
  {
    id: 50,
    product_name: "Bread - Mini Hamburger Bun",
    product_number: { $oid: "65bb40e6fc13ae52c123466f" },
    product_category: "Labordia kaalae Forbes",
    product_weight: 12,
    product_price: 39,
  },
  {
    id: 51,
    product_name: "Cup - Paper 10oz 92959",
    product_number: { $oid: "65bb40e6fc13ae52c1234670" },
    product_category:
      "Penstemon barbatus (Cav.) Roth ssp. torreyi (Benth.) D.D. Keck",
    product_weight: 44,
    product_price: 42,
  },
  {
    id: 52,
    product_name: "Wine - Rosso Del Veronese Igt",
    product_number: { $oid: "65bb40e6fc13ae52c1234671" },
    product_category: "Monardella beneolens Shevock, Ertter & Jokerst",
    product_weight: 30,
    product_price: 53,
  },
  {
    id: 53,
    product_name: "Pork - Tenderloin, Frozen",
    product_number: { $oid: "65bb40e6fc13ae52c1234672" },
    product_category: "Sporobolus neglectus Nash",
    product_weight: 65,
    product_price: 99,
  },
  {
    id: 54,
    product_name: "Cheese - Havarti, Salsa",
    product_number: { $oid: "65bb40e6fc13ae52c1234673" },
    product_category:
      "Rhododendron occidentale (Torr. & A. Gray) A. Gray var. sonomense (Greene) Rehder",
    product_weight: 77,
    product_price: 40,
  },
  {
    id: 55,
    product_name: "Juice - Orange 1.89l",
    product_number: { $oid: "65bb40e6fc13ae52c1234674" },
    product_category: "Paspalidium geminatum (Forssk.) Stapf",
    product_weight: 80,
    product_price: 28,
  },
  {
    id: 56,
    product_name: "Vinegar - Balsamic",
    product_number: { $oid: "65bb40e6fc13ae52c1234675" },
    product_category:
      "Ericameria nauseosa (Pall. ex Pursh) G.L. Nesom & Baird ssp. nauseosa var. iridis (L.C. Anderson) G.L. Nesom & Baird",
    product_weight: 27,
    product_price: 61,
  },
  {
    id: 57,
    product_name: "Parsnip",
    product_number: { $oid: "65bb40e6fc13ae52c1234676" },
    product_category: "Hibiscus biseptus S. Watson",
    product_weight: 18,
    product_price: 89,
  },
  {
    id: 58,
    product_name: "Chef Hat 20cm",
    product_number: { $oid: "65bb40e6fc13ae52c1234677" },
    product_category: "Paulownia Siebold & Zucc.",
    product_weight: 90,
    product_price: 88,
  },
  {
    id: 59,
    product_name: "Olives - Nicoise",
    product_number: { $oid: "65bb40e6fc13ae52c1234678" },
    product_category: "Thelidium areolatum J.W. Thomson",
    product_weight: 98,
    product_price: 25,
  },
  {
    id: 60,
    product_name: "Table Cloth 53x53 White",
    product_number: { $oid: "65bb40e6fc13ae52c1234679" },
    product_category: "Dodecatheon dentatum Hook.",
    product_weight: 77,
    product_price: 24,
  },
  {
    id: 61,
    product_name: "Chicken - Breast, 5 - 7 Oz",
    product_number: { $oid: "65bb40e6fc13ae52c123467a" },
    product_category: "Passiflora gracilis Jacq. ex Link",
    product_weight: 21,
    product_price: 54,
  },
  {
    id: 62,
    product_name: "Cookie Double Choco",
    product_number: { $oid: "65bb40e6fc13ae52c123467b" },
    product_category: "Lescuraea Schimp.",
    product_weight: 3,
    product_price: 81,
  },
  {
    id: 63,
    product_name: "Nantucket - Kiwi Berry Cktl.",
    product_number: { $oid: "65bb40e6fc13ae52c123467c" },
    product_category: "Caragana aurantiaca Koehne",
    product_weight: 47,
    product_price: 91,
  },
  {
    id: 64,
    product_name: "Cups 10oz Trans",
    product_number: { $oid: "65bb40e6fc13ae52c123467d" },
    product_category: "Eriogonum hemipterum (Torr.) S. Stokes",
    product_weight: 71,
    product_price: 14,
  },
  {
    id: 65,
    product_name: "Fuji Apples",
    product_number: { $oid: "65bb40e6fc13ae52c123467e" },
    product_category: "Layia gaillardioides (Hook. & Arn.) DC.",
    product_weight: 6,
    product_price: 81,
  },
  {
    id: 66,
    product_name: "Mix Pina Colada",
    product_number: { $oid: "65bb40e6fc13ae52c123467f" },
    product_category: "Pisonia subcordata Sw.",
    product_weight: 82,
    product_price: 47,
  },
  {
    id: 67,
    product_name: "Greens Mustard",
    product_number: { $oid: "65bb40e6fc13ae52c1234680" },
    product_category: "Quercus prinoides Willd.",
    product_weight: 36,
    product_price: 97,
  },
  {
    id: 68,
    product_name: "Lemonade - Island Tea, 591 Ml",
    product_number: { $oid: "65bb40e6fc13ae52c1234681" },
    product_category: "Rhododon ciliatus (Benth.) Epling",
    product_weight: 98,
    product_price: 31,
  },
  {
    id: 69,
    product_name: "Doilies - 12, Paper",
    product_number: { $oid: "65bb40e6fc13ae52c1234682" },
    product_category: "Spiraea douglasii Hook.",
    product_weight: 33,
    product_price: 53,
  },
  {
    id: 70,
    product_name: "Lettuce - Sea / Sea Asparagus",
    product_number: { $oid: "65bb40e6fc13ae52c1234683" },
    product_category: "Pinus longaeva D.K. Bailey",
    product_weight: 76,
    product_price: 7,
  },
  {
    id: 71,
    product_name: "Island Oasis - Mango Daiquiri",
    product_number: { $oid: "65bb40e6fc13ae52c1234684" },
    product_category: "Cynodon transvaalensis Burtt Davy",
    product_weight: 98,
    product_price: 46,
  },
  {
    id: 72,
    product_name: "Duck - Fat",
    product_number: { $oid: "65bb40e6fc13ae52c1234685" },
    product_category: "Caulanthus coulteri S. Watson",
    product_weight: 37,
    product_price: 82,
  },
  {
    id: 73,
    product_name: "Browning Caramel Glace",
    product_number: { $oid: "65bb40e6fc13ae52c1234686" },
    product_category: "Lesquerella obdeltata Rollins",
    product_weight: 96,
    product_price: 70,
  },
  {
    id: 74,
    product_name: "Bread - Wheat Baguette",
    product_number: { $oid: "65bb40e6fc13ae52c1234687" },
    product_category:
      "Jacquemontia ovalifolia (Vahl ex West) Hallier f. ssp. sandwicensis (A. Gray) K.R. Robertson",
    product_weight: 14,
    product_price: 32,
  },
  {
    id: 75,
    product_name: "Rabbit - Legs",
    product_number: { $oid: "65bb40e6fc13ae52c1234688" },
    product_category: "Angelica archangelica L. ssp. norvegica (Rupr.) Nordh.",
    product_weight: 90,
    product_price: 18,
  },
  {
    id: 76,
    product_name: "Lettuce - Curly Endive",
    product_number: { $oid: "65bb40e6fc13ae52c1234689" },
    product_category: "Momordica L.",
    product_weight: 92,
    product_price: 7,
  },
  {
    id: 77,
    product_name: "Carbonated Water - Blackberry",
    product_number: { $oid: "65bb40e6fc13ae52c123468a" },
    product_category: "Iris prismatica Pursh ex Ker Gawl.",
    product_weight: 53,
    product_price: 49,
  },
  {
    id: 78,
    product_name: "V8 Splash Strawberry Banana",
    product_number: { $oid: "65bb40e6fc13ae52c123468b" },
    product_category:
      "Arceuthobium abietinum (Engelm.) Hawksw. & Wiens ssp. wiensii Mathiasen & C.M. Daugherty",
    product_weight: 9,
    product_price: 5,
  },
  {
    id: 79,
    product_name: "Wine - Ej Gallo Sonoma",
    product_number: { $oid: "65bb40e6fc13ae52c123468c" },
    product_category: "Zapoteca formosa (Kunth) H.M. Hern.",
    product_weight: 48,
    product_price: 50,
  },
  {
    id: 80,
    product_name: "Extract Vanilla Pure",
    product_number: { $oid: "65bb40e6fc13ae52c123468d" },
    product_category: "Rubus plus L.H. Bailey",
    product_weight: 23,
    product_price: 76,
  },
  {
    id: 81,
    product_name: "Food Colouring - Red",
    product_number: { $oid: "65bb40e6fc13ae52c123468e" },
    product_category: "Spermolepis echinata (Nutt. ex DC.) A. Heller",
    product_weight: 72,
    product_price: 57,
  },
  {
    id: 82,
    product_name: "Cumin - Ground",
    product_number: { $oid: "65bb40e6fc13ae52c123468f" },
    product_category: "Anoectangium tenuinerve (Limpr.) Par.",
    product_weight: 45,
    product_price: 86,
  },
  {
    id: 83,
    product_name: "Turkey - Whole, Fresh",
    product_number: { $oid: "65bb40e6fc13ae52c1234690" },
    product_category: "Laportea interrupta (L.) Chew",
    product_weight: 40,
    product_price: 35,
  },
  {
    id: 84,
    product_name: "Bag Clear 10 Lb",
    product_number: { $oid: "65bb40e6fc13ae52c1234691" },
    product_category: "Plagiobothrys bracteatus (Howell) I.M. Johnst.",
    product_weight: 7,
    product_price: 28,
  },
  {
    id: 85,
    product_name: "Eel Fresh",
    product_number: { $oid: "65bb40e6fc13ae52c1234692" },
    product_category: "Encalypta sibirica (Weinm.) Warnst.",
    product_weight: 7,
    product_price: 7,
  },
  {
    id: 86,
    product_name: "Roe - Flying Fish",
    product_number: { $oid: "65bb40e6fc13ae52c1234693" },
    product_category: "Cypripedium guttatum Sw.",
    product_weight: 50,
    product_price: 7,
  },
  {
    id: 87,
    product_name: "Egg Patty Fried",
    product_number: { $oid: "65bb40e6fc13ae52c1234694" },
    product_category: "Spiraea ×hitchcockii Hess & Stoynoff",
    product_weight: 24,
    product_price: 95,
  },
  {
    id: 88,
    product_name: "Steampan - Foil",
    product_number: { $oid: "65bb40e6fc13ae52c1234695" },
    product_category: "Arabis pendulina Greene",
    product_weight: 13,
    product_price: 20,
  },
  {
    id: 89,
    product_name: "Island Oasis - Pina Colada",
    product_number: { $oid: "65bb40e6fc13ae52c1234696" },
    product_category: "Leptogium cyanescens (Rabenh.) Körb.",
    product_weight: 64,
    product_price: 90,
  },
  {
    id: 90,
    product_name: "Shiratamako - Rice Flour",
    product_number: { $oid: "65bb40e6fc13ae52c1234697" },
    product_category: "Horkelia congesta Douglas ex Hook. ssp. congesta",
    product_weight: 95,
    product_price: 13,
  },
  {
    id: 91,
    product_name: "Mustard - Dijon",
    product_number: { $oid: "65bb40e6fc13ae52c1234698" },
    product_category: "Allium macrum S. Watson",
    product_weight: 54,
    product_price: 32,
  },
  {
    id: 92,
    product_name: "Pork Loin Bine - In Frenched",
    product_number: { $oid: "65bb40e6fc13ae52c1234699" },
    product_category: "Everniastrum Hale ex Sipman",
    product_weight: 10,
    product_price: 32,
  },
  {
    id: 93,
    product_name: "Garlic Powder",
    product_number: { $oid: "65bb40e6fc13ae52c123469a" },
    product_category: "Vestergrenopsis elaeina (Wahlenb.) Gyel.",
    product_weight: 59,
    product_price: 54,
  },
  {
    id: 94,
    product_name: "Sauce - Apple, Unsweetened",
    product_number: { $oid: "65bb40e6fc13ae52c123469b" },
    product_category: "Trypethelium ochroleucum (Eschw.) Nyl.",
    product_weight: 8,
    product_price: 50,
  },
  {
    id: 95,
    product_name: "Pastry - Butterscotch Baked",
    product_number: { $oid: "65bb40e6fc13ae52c123469c" },
    product_category:
      "Woodsia oregana D.C. Eaton ssp. cathcartiana (B.L. Rob.) Windham",
    product_weight: 86,
    product_price: 57,
  },
  {
    id: 96,
    product_name: "Oil - Food, Lacquer Spray",
    product_number: { $oid: "65bb40e6fc13ae52c123469d" },
    product_category: "Sphaeralcea laxa Wooton & Standl.",
    product_weight: 43,
    product_price: 97,
  },
  {
    id: 97,
    product_name: "Lobster - Tail, 3 - 4 Oz",
    product_number: { $oid: "65bb40e6fc13ae52c123469e" },
    product_category: "Paspalum laxum Lam.",
    product_weight: 9,
    product_price: 83,
  },
  {
    id: 98,
    product_name: "Cookies Oatmeal Raisin",
    product_number: { $oid: "65bb40e6fc13ae52c123469f" },
    product_category: "Lesquerella purpurea (A. Gray) S. Watson",
    product_weight: 73,
    product_price: 6,
  },
  {
    id: 99,
    product_name: "Chervil - Fresh",
    product_number: { $oid: "65bb40e6fc13ae52c12346a0" },
    product_category: "Ichnanthus pallens (Sw.) Munro ex Benth. var. pallens",
    product_weight: 55,
    product_price: 54,
  },
  {
    id: 100,
    product_name: "Tuna - Fresh",
    product_number: { $oid: "65bb40e6fc13ae52c12346a1" },
    product_category:
      "Helianthus nuttallii Torr. & A. Gray ssp. parishii (A. Gray) Heiser",
    product_weight: 96,
    product_price: 23,
  },
];

export { datas, datas2 };
